---
- hosts: all
  become: True
  become_method: sudo
  tasks:

    - name: Deploy static website
      copy:
        src: /var/lib/jenkins/workspace/project3 # We have define a html page
        dest: /opt/tomcat/webapps/war/
