---
- hosts: all
  become: True
  become_method: sudo
  tasks:

    - name: Unzip WAR file
      unarchive: src=/var/lib/jenkins/workspace/project3/webapps/webapptest.war dest=/usr/local/tomcat/webapps 
